title: DH in the Classroom
description: 'Testing out static site concepts'
theme: jekyll-theme-time-machine

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: post
